#!/usr/bin/env bash
#
# This script is invoked after the createimg script copied the root partition
# to the mounted image.
#
# The first argument is the folder of the mounted root partition.
# The second argument is the folder of the source root file system before it
# was copied to the mounted partition.  Some folders like /boot, /media, /root,
# and /tmp are not copied to the mounted partition.
#
if [ -e /etc/ld.so.preload.disabled ]; then
	mv /etc/ld.so.preload.disabled /etc/ld.so.preload
fi
