#!/usr/bin/env bash
set -e

#
# NOTE: This script is run within the chroot after second stage debootstrap!
#

set -e

if [ "$#" -eq 8 ]; then
	echo "Usage: $0 DIST ARCH LOCALE UNAME UPASS RPASS INC_REC"
	exit 1
fi

DIST=$1
ARCH=$2
LOCALE=$3
UNAME=$4
UPASS=$5
RPASS=$6
INC_REC=$7

echo "Running postinstall script..."

# Sanitize environnement
LC_ALL=C
LANG=C

# Make dpkg/apt-get noninteractive
export DEBIAN_FRONTEND=noninteractive

# For now there is only one avail, but we will check ARCH to set this in the
# future (For flash-kernel)
export FK_MACHINE="Raspberry Pi 2 Model B"

# Prevent apt-get from starting services
echo "#!/bin/sh
exit 101
" > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d

# Set the locale
ln -s /usr/share/i18n/SUPPORTED /etc/locale.gen
sed -i -e 's/^ *[a-zA-Z]/# &/' /etc/locale.gen
sed -i "s/^#[[:space:]]*${LOCALE}\(.*\)/${LOCALE}\1/g" /etc/locale.gen
echo "LANG=${LOCALE}" >> /etc/default/locale
echo "locales locales/default_environment_locale select ${LOCALE}" | debconf-set-selections
echo "locales locales/locales_to_be_generated select ${LOCALE} UTF-8" | debconf-set-selections
locale-gen

# Finish multistrap
/var/lib/dpkg/info/base-passwd.preinst install
/var/lib/dpkg/info/dash.preinst install
dpkg --force-all --configure debconf mawk
dpkg --configure -a

# Set root password
echo "root:${RPASS}" | chpasswd

# Add user $UNAME
useradd -m ${UNAME} -s /bin/bash

# Set $UNAME password
echo "${UNAME}:${UPASS}" | chpasswd

# Add $UNAME to sudo group
adduser ${UNAME} sudo
adduser ${UNAME} audio
adduser ${UNAME} video

# Initialize /etc/apt/sources.list (remove multistrap from the filenames)
for i in /etc/apt/sources.list.d/*; do
	mv $i $(dirname $i)/$(echo $i | cut -d"-" -f2);
done

apt-get update

APTOPTS=""
if [ "$INC_APT" == "1" ]; then
	$APTOPTS="$APTOPTS --no-install-recommends";
fi

# Install extra packages
if [ -f /packages.txt ]; then
	apt-get -y --assume-yes install $(cat /packages.txt) $APTOPTS;
fi

# Run custom install scripts
if [ -d /postinst ]; then
	echo "Running custom postinst scripts"
	for i in `find /postinst -maxdepth 1 -type f -executable -not -name "*~"`; do
		echo "  Running $i"
		$i
	done
else
	echo "No custom postinst scripts found"
fi

# Run custom install scripts for a specific distribution
if [ -d /postinst/${DIST} ]; then
	echo "Running custom ${DIST} postinst scripts"
	for i in `find /postinst/${DIST} -maxdepth 1 -type f -executable -not -name "*~"`; do
		echo "  Running $i"
		$i
	done
else
	echo "No custom ${DIST} postinst scripts found"
fi

# Re-enable services to start
rm /usr/sbin/policy-rc.d

# Cleanup
echo "Running clean up"
rm -f /etc/hostname
rm -f /etc/ssh/ssh_host_*
apt-get autoclean
apt-get clean
dpkg --clear-avail
