#!/usr/bin/env bash
set -e

cat <<'EOF' >> /etc/sysctl.conf

# Raspberry Pi Tweaks
# http://www.raspberrypi.org/forums/viewtopic.php?p=104096#p104096
vm.swappiness = 1
vm.min_free_kbytes = 8192
vm.vfs_cache_pressure = 50
vm.dirty_writeback_centisecs = 1500
vm.dirty_ratio = 20
vm.dirty_background_ratio = 10
EOF
