#!/bin/sh

# see Chapter 8 of Debian Linux Kernel Handbook

set -e

# conffile still present, but flash-kernel removed
if ! which flash-kernel >/dev/null 2>&1; then
    exit 0
fi

rsync --quiet --archive --devices --specials --hard-links --acls --xattrs --sparse --copy-links --exclude '/boot/firmware/' /boot/* /boot/firmware
