#!/usr/bin/env bash
set -e

ubootdir=$2

# Set RPi kernel cmdline
echo "flash-kernel flash-kernel/linux_cmdline string earlyprintk dwc_otg.lpm_enable=0 console=ttyS0,115200 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait" | debconf-set-selections

dpkg-reconfigure -f noninteractive flash-kernel

cp /usr/lib/u-boot/${ubootdir}/* /boot/firmware/
echo "$FK_MACHINE" > /etc/flash-kernel/machine

unset FLASH_KERNEL_SKIP
if [ "$RIB_DIST" = "Ubuntu" ]; then
	flash-kernel $FK_MACHINE
else
	flash-kernel
fi

/etc/kernel/postinst.d/zzz-fatboot-partition

if grep 'snd_bcm2835' /etc/modules > /dev/null; then
	sed -i -e 's,snd_bcm2835,snd-soc-bcm2835-i2s,g' /etc/modules
elif ! grep 'snd*bcm2835' /etc/modules > /dev/null; then
	echo 'snd-soc-bcm2835-i2s' >> /etc/modules
fi
