#!/usr/bin/env bash
set -e

ubootdir=$2

# Set RPi kernel cmdline
echo "flash-kernel flash-kernel/linux_cmdline string earlyprintk dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait" | debconf-set-selections

dpkg-reconfigure -f noninteractive flash-kernel

cp /usr/lib/u-boot/${ubootdir}/* /boot/firmware/

unset FLASH_KERNEL_SKIP
if [ "$RIB_DIST" = "Ubuntu" ]; then
	flash-kernel $FK_MACHINE
else
	flash-kernel
fi

/etc/kernel/postinst.d/zzz-fatboot-partition
