#!/usr/bin/env bash
set -e

git clone --depth 1 https://github.com/raspberrypi/firmware.git /tmp/firmware
mkdir -p rootfs/boot/firmware/
cp /tmp/firmware/boot/*.bin rootfs/boot/firmware/
cp /tmp/firmware/boot/*.elf rootfs/boot/firmware/
cp /tmp/firmware/boot/*.dat rootfs/boot/firmware/

rm -rf /tmp/firmware
