#!/usr/bin/env bash
set -e

mkdir -p /lib/systemd/system/sysinit.target.wants
ln -s ../createhs.service /lib/systemd/system/sysinit.target.wants/createhs.service
systemctl daemon-reload

if [ -e /disable-root-fs ]; then
	mv disable-root-fs disable-root-fs.wait
fi

touch /var/tmp/system-hostname
