#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          resize2fs_last
# Required-Start: $local_fs
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

. /lib/lsb/init-functions

if [ ! -f /var/tmp/ROOT_RESIZE ]; then
	exit 0
fi

do_finish_expand_rootfs() {
	resize2fs /dev/mmcblk0p2
}

case "$1" in
	start)
		log_daemon_msg "Starting resize2fs_last" &&
		do_finish_expand_rootfs &&
		update-rc.d resize2fs_last remove &&
		rm -f /etc/init.d/resize2fs_last &&
		rm -f /var/tmp/ROOT_RESIZE &&
		rm -f /var/tmp/system-resizefs &&
		log_end_msg $?

		if [ -f /var/tmp/system-* ]; then
			reboot
		fi
	;;
	*)
		echo "Usage: $0 start" >&2
		exit 3
	;;
esac

exit 0
