#!/bin/bash -e
### BEGIN INIT INFO
# Provides: dbreconfig
# Required-Start: $all
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: Reconfigure dbconfig scripts
# Description:
### END INIT INFO

. /lib/lsb/init-functions

if [ ! -e /var/run/ROOT_RESIZED ]; then
	exit 0;
fi

DO_REBOOT=0

do_reconf() {
	if [ -d /etc/dbconfig-common ] && [ -e /etc/dbconfig-common/*.conf ]; then
		for i in /etc/dbconfig-common/*.conf; do
			PKGNAME=$(dpkg -S $i | cut -d: -f1)
			DEBIAN_FRONTEND=noninteractive /var/lib/dpkg/info/${PKGNAME}.postinst configure
			DO_REBOOT=1
		done
	fi
}

case "$1" in
	start)
		log_daemon_msg "Starting dbreconfig" &&
		do_reconf &&
		rm /etc/init.d/dbreconfig &&
		update-rc.d dbreconfig remove &&
		log_end_msg $? &&
		if [ $DO_REBOOT == 1 ]; then reboot; fi
	;;
	*)
		echo "Usage: $0 start" >&2
		exit 3
	;;
esac

exit 0
